### ISSUE TITLE
Openseadragon issues

### ISSUE THREAD

**Issue by vipul-21** [informatics-isi-edu/openseadragon-viewer#20]
### Multi-Scene Issue
1. Tiff type image - Currently it handles multi scene by treating each url as a separate scene. If there are channels associated with the tiff, then all the channels will be associated with all the scenes instead of associating with respective scene. For example - `url=path1.tiff&channelName=x1&url=path2.tiff&channelName=x2` will have 2 scenes with 2 channels with both the channel associating with both scenes instead of their respective scenes only.
2. For xml or jpeg or png type image - Currently they are handling multiple channels associated with a single scene. Multiple scene with multiple channel with the current version won't behave in the desired manner. Need to rectify that.
If there are multiple scene, without any channels -  need to see how osd behave in that case, as we're passing the url to osd library to render the scenes.
3. AliasName currently is used to display in place of channel name whenever AliasName is available.(Instead of changing the channel name to alias name - we can use the tooltip to show the alias name)

**Comment by carlkesselman** [comment]
I *REALLY* don’t think we should be wasting any time on multi-scene images. We should assume that our tiff have only a single scene in them, which in OME-TIFF is called a series. TIFF as a format knows nothing about scenes or channels. These are concepts that are the result of interpreting multiple 2D image planes as being related somehow. I think it is a mistake to try to deal with any other multi-plane convention than OME-TIFF organization’s, and we should assume that what OSD has available to it is a separate file for each zplane-channel, and that the associated file has only a single image in it.


Also, I think we should not be working about jpeg or png to be honest. I think we should hide everything behind our image server. Then if we have multiple channels the treatment is exactly the same.

So my suggestion is that going forward we focus on using our image server, which will provide a uniform interface on top of all of the different image types, and we assume that there is a single image at a time, not multiple scenes, and that we have a different named resource (filename/url) for every Z plane and channel that follows a naming convention and that that convention holds even if we have a single zplane and channel (ie. 0_0).

Carl


----------------------------------------------------------

Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute Viterbi School of Engineering Professor,

Preventive Medicine Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
 Email:  carl@isi.edu
Web: http://www.isi.edu/~carl
On May 15, 2020, 7:16 PM -0700, Vipul Singh <notifications@github.com>, wrote:

Multi-Scene Issue

  1.  Tiff type image - Currently it handles multi scene by treating each url as a separate scene. If there are channels associated with the tiff, then all the channels will be associated with all the scenes instead of associating with respective scene. For example - url=path1.tiff&channelName=x1&url=path2.tiff&channelName=x2 will have 2 scenes with 2 channels with both the channel associating with both scenes instead of their respective scenes only.
  2.  For xml or jpeg or png type image - Currently they are handling multiple channels associated with a single scene. Multiple scene with multiple channel with the current version won't behave in the desired manner. Need to rectify that.
If there are multiple scene, without any channels - need to see how osd behave in that case, as we're passing the url to osd library to render the scenes.
  3.  AliasName currently is used to display in place of channel name whenever AliasName is available.(Instead of changing the channel name to alias name - we can use the tooltip to show the alias name)

**Comment by RFSH** [comment]
With the changes in #51, by default we will treat each image as a representation of a channel. If a set of images is given, OSD viewer will display them in a multi-channel view.

We don't plan on supporting mutli-scene view for now and instead we are going to make some modifications to support a multi-z viewer (#57).
