### ISSUE TITLE
Explore jump to Z-index / slider feature

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/openseadragon-viewer#67]
@rastogi-bhavya _please update the issue with more information. You mainly should list whatever you think works and iterate over all the pros and cons. You don’t need to fully implement any of them. just come up with different ways to achieve these. It’s a lost easier to discuss this when one of us (in case you) have gone through all the iterations and thought about different pros and cons_

**Comment by rastogi-bhavya** [comment]
### Jump to Z Index
1. Provide an input box to the user which will allow him to enter the desired index
2. If the index entered by the user exists, update to show that particular plane in the OSD, update the z-plane container such that the desired index is the center one in the carousel.
3. If the index does not exist use the closest index to the input, and show a pop-up (or some other UI) to indicate to the user that the index is not present in the database.

**Comment by rastogi-bhavya** [comment]
### Slider Feature
From the carousels that I have seen, slider is only possible when the carousel is free flowing and not paginated.

One way to implement a slider would be to have a slider to select the index

|--|--|--|--|--|--|--|--|--|

Each of the `|` would mark an index and dragging the slider would jump to that particular index (having the same UI behavior as the `Jump to Z Index`).

To implement this a list of indexes would be needed before hand so that they could be mapped. https://www.w3schools.com/howto/howto_js_rangeslider.asp
